export const pets = [
    {
        ID_pet: 1,
        nome_pet: "Egg",
        caminho_pet: "Egg.gif",
        desc_pet: "Um ovo misterioso e curioso.",
        ponto_pet: 0,
        raridade_pet: "Comum",
        peso_pet: 0,
    },
    {
        ID_pet: 2,
        nome_pet: "Gentle Bunny",
        caminho_pet: "GentleBunny.gif",
        desc_pet: "Um coelhinho elegante e charmoso.",
        ponto_pet: 100,
        raridade_pet: "Comum",
        peso_pet: 0.6,
    },
    {
        ID_pet: 3,
        nome_pet: "Monkey Black",
        caminho_pet: "MonkeyGif_black.gif",
        desc_pet: "Um macaco misterioso e sombrio.",
        ponto_pet: 50,
        raridade_pet: "Raro",
        peso_pet: 0.2,
    },
    {
        ID_pet: 4,
        nome_pet: "Golden Shadow Monkey",
        caminho_pet: "MonkeyGif_douradoblack.gif",
        desc_pet: "Um macaco dourado com mistérios ocultos.",
        ponto_pet: 500,
        raridade_pet: "Lendário",
        peso_pet: 0.005,
    },
    {
        ID_pet: 5,
        nome_pet: "Pink Power Monkey",
        caminho_pet: "MonkeyGif_powerpink.gif",
        desc_pet: "Um macaco rosa cheio de energia.",
        ponto_pet: 200,
        raridade_pet: "Épico",
        peso_pet: 0.1,
    },
    {
        ID_pet: 6,
        nome_pet: "Cute Purple Monkey",
        caminho_pet: "MonkeyGif_roxinho.gif",
        desc_pet: "Um adorável macaco roxo.",
        ponto_pet: 80,
        raridade_pet: "Incomum",
        peso_pet: 0.4,
    },
    {
        ID_pet: 7,
        nome_pet: "Happy Rainbow Monkey",
        caminho_pet: "MonkeyGif_animadinha.gif",
        desc_pet: "Um macaco alegre com um arco-íris.",
        ponto_pet: 120,
        raridade_pet: "Comum",
        peso_pet: 0.6,
    },
    {
        ID_pet: 8,
        nome_pet: "Avatar Monkey",
        caminho_pet: "MonkeyGif_avatar.gif",
        desc_pet: "Um macaco que controla os elementos.",
        ponto_pet: 400,
        raridade_pet: "Épico",
        peso_pet: 0.1,
    },
];

console.log(pets);
